# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ca075b9b59d55c7c99dc7c09f61c372a026bdf8d4cd549d409668c5e45c3d023274425522f70a3fc235ad253b729b135f9219e15c04ea12ae1bb19b978f374

test:
  secret_key_base: 7ce3f279938bf7c0780122e7c4b0483cdb8811ca32d58af34ffe99bf2c79557a934ddd508dd23e321187e6a7be0223d63653cc4090ae66a83b04f50af9080672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
